#!/bin/bash
stagedFiles=$(git diff-index --cached HEAD | grep ".php" | grep "^:" | sed 's:[^/]*[DAM][ \\''w]*\([^ \\''w]*\):\1:g');

phpLintErrors=0
echo "PHP will now lint all the php staged files..."
for file in $stagedFiles
do
	php -l $file
	RETVAL=$?
	if [[ $RETVAL != 0 ]]
	then
		phpLintErrors=1
	fi
done

if [[ $phpLintErrors == 1 ]]
then
	RED='\e[101m'
	NC='\e[0m'
	red='\e[1;31m'
	white='\e[1;37m'
	line='---------------------------------------------------'
	echo ""
	echo -e "${RED}${red}${line}"
	echo -e "${white} Please, correct the errors above. COMMIT ABORTED! "
	echo -e "${red}${line}${NC}"
	echo ""
	exit 1
else
	exit 0
fi
